package middleware.dto;

import lombok.Data;

/**
 * Data Transfer Object (DTO) for representing a JWT request.
 *
 * <p>This class encapsulates a single JWT, which is used to identify
 * a user or an entity in the system. It provides getter and setter methods,
 * along with {@code equals()}, {@code hashCode()}, and {@code toString()} implementations,
 * generated by the <a href="https://projectlombok.org/features/Data" target="_blank">Lombok @Data</a> annotation.
 */
@Data
public class JWTRequest {
    private String jwt;
}
