services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /Backend/Tournament_Public
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
      - MYSQL_DATABASE=tournament_db
    volumes:
      - .:/Backend/Tournament_Public
      - /Backend/Tournament_Public/node_modules
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=tournament_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data: