version: '3.8'

services:
  spring-app:
    image: user-msvc  # The image name from the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose the application on port 8080
    volumes:
      - ./src/main/resources:/app/src/main/resources  # Mount resources folder
