package TournamentAdminService;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import TournamentAdminService.model.Tournament;
import TournamentAdminService.repository.TournamentRepository;
import TournamentAdminService.service.TournamentService;

import java.sql.Date;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

/**
 * Test class for TournamentService, focusing on CRUD operations for the Tournament entity.
 */
public class TournamentAdminServiceTest {

    @InjectMocks
    private TournamentService tournamentService;

    @Mock
    private TournamentRepository tournamentRepository;

    private Tournament tournament;

    /**
     * Initializes mock objects and a sample Tournament instance before each test.
     */
    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        tournament = new Tournament();
        tournament.setName("Championship");
        tournament.setStartDate(LocalDate.of(2024, 10, 1));
        tournament.setEndDate(LocalDate.of(2024, 10, 5));
        tournament.setLocation("Stadium A");
        tournament.setPlayerLimit(16);
        tournament.setStatus("Completed");
        tournament.setDescOID("Description of Tournament");
    }

    /**
     * Tests the creation of a tournament by verifying that the repository's createTournament
     * method is called once with the appropriate parameters.
     */
    @Test
    public void testCreateTournament() {
        // Act
        tournamentService.createTournament(tournament);

        // Assert
        verify(tournamentRepository, times(1)).createTournament(
                anyString(), 
                any(Date.class), 
                any(Date.class), 
                anyString(), 
                anyInt(), 
                anyString(), 
                anyString()
        );
    }

    /**
     * Tests retrieving a tournament by ID, ensuring the correct tournament data is returned.
     */
    @Test
    public void testGetTournamentById() {
        when(tournamentRepository.getTournamentById(anyString())).thenReturn(tournament);
        Tournament retrievedTournament = tournamentService.getTournamentById("T001");
        assertEquals("Championship", retrievedTournament.getName());
    }

    /**
     * Tests updating a tournament by verifying that the repository's updateTournament
     * method is called with appropriate parameters.
     */
    @Test
    public void testUpdateTournament() {
        // Set an ID to simulate it being generated by the system
        tournament.setTournamentID("GeneratedID");

        // Act
        tournamentService.updateTournament(tournament);

        // Assert
        verify(tournamentRepository, times(1)).updateTournament(
                anyString(), 
                anyString(),
                any(Date.class), 
                any(Date.class), 
                anyString(), 
                anyInt(), 
                anyString(), 
                anyString()
        );
    }

    /**
     * Tests deleting a tournament by verifying that the repository's deleteTournament
     * method is called with the correct ID.
     */
    @Test
    public void testDeleteTournament() {
        tournament.setTournamentID("GeneratedID"); // Simulate an ID assigned by the system

        // Act
        tournamentService.deleteTournament("GeneratedID");

        // Assert
        verify(tournamentRepository, times(1)).deleteTournament("GeneratedID");
    }

    /**
     * Tests retrieving all tournaments by checking that the list returned by the service
     * matches the expected data.
     */
    @Test
    public void testGetAllTournaments() {
        when(tournamentRepository.getAllTournaments()).thenReturn(Arrays.asList(tournament));
        List<Tournament> tournaments = tournamentService.getAllTournaments();

        // Assert
        assertEquals(1, tournaments.size());
        assertEquals("Championship", tournaments.get(0).getName());
    }
}