version: '3.8'

services:
  tournament-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources:/app/src/main/resources  
    