name: pre-commit

on:
  pull_request:
    branches-ignore: [main]
  push:
    branches-ignore: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        chmod +x ./git-hooks/pre-commit/check-gitignore.sh
        chmod +x ./git-hooks/pre-commit/check-staged-files.sh
        pip install pre-commit
        pre-commit run
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()