name: pre-commit

on:
  pull_request:
    branches-ignore: [main]
  push:
    branches-ignore: [main]
    paths:
      - 'Backend/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3